name: triage_bios_ai
description: "Triage-BIOS.ai - Vital Intelligence for Critical Decisions"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # Essential UI
  cupertino_icons: ^1.0.8

  # State Management
  flutter_bloc: ^9.1.1

  # JSON Serialization
  json_annotation: ^4.9.0

  # Multi-modal input
  image_picker: ^1.0.7
  # speech_to_text: ^7.2.0 # Temporarily disabled due to Android Kotlin compatibility issues
  flutter_tts: ^4.0.2

  # Health & Wearables
  health: ^13.1.1

  # Location & Maps
  geolocator: ^14.0.2
  google_maps_flutter: ^2.9.0

  # Internationalization
  intl: ^0.20.2

  # Configuration & Environment
  flutter_dotenv: ^5.1.0

  # Essential utilities
  http: ^1.2.2
  dio: ^5.7.0
  shared_preferences: ^2.3.2
  logger: ^2.4.0
  equatable: ^2.0.5
  dartz: ^0.10.1
  uuid: ^4.5.1
  crypto: ^3.0.3
  web_socket_channel: ^2.4.0

  # Firebase
  firebase_core: ^3.6.0
  cloud_firestore: ^5.6.12
  firebase_auth: ^5.3.1
  firebase_storage: ^12.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

  # Testing
  mockito: ^5.4.4
  integration_test:
    sdk: flutter
  test: ^1.25.8

  # Code Generation
  build_runner: ^2.4.13
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
