// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'config/app_config.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions get web => FirebaseOptions(
    apiKey: AppConfig.instance.firebaseWebApiKey,
    appId: AppConfig.instance.firebaseWebAppId,
    messagingSenderId: AppConfig.instance.firebaseMessagingSenderId,
    projectId: AppConfig.instance.firebaseProjectId,
    authDomain: AppConfig.instance.firebaseAuthDomain,
    storageBucket: AppConfig.instance.firebaseStorageBucket,
    measurementId: AppConfig.instance.firebaseMeasurementId,
  );

  static FirebaseOptions get android => FirebaseOptions(
    apiKey: AppConfig.instance.firebaseAndroidApiKey,
    appId: AppConfig.instance.firebaseAndroidAppId,
    messagingSenderId: AppConfig.instance.firebaseMessagingSenderId,
    projectId: AppConfig.instance.firebaseProjectId,
    storageBucket: AppConfig.instance.firebaseStorageBucket,
  );

  static FirebaseOptions get ios => FirebaseOptions(
    apiKey: AppConfig.instance.firebaseIosApiKey,
    appId: AppConfig.instance.firebaseIosAppId,
    messagingSenderId: AppConfig.instance.firebaseMessagingSenderId,
    projectId: AppConfig.instance.firebaseProjectId,
    storageBucket: AppConfig.instance.firebaseStorageBucket,
    iosBundleId: AppConfig.instance.firebaseIosBundleId,
  );

  static FirebaseOptions get macos => FirebaseOptions(
    apiKey: AppConfig.instance.firebaseIosApiKey,
    appId: AppConfig.instance.firebaseIosAppId,
    messagingSenderId: AppConfig.instance.firebaseMessagingSenderId,
    projectId: AppConfig.instance.firebaseProjectId,
    storageBucket: AppConfig.instance.firebaseStorageBucket,
    iosBundleId: AppConfig.instance.firebaseIosBundleId,
  );

  static FirebaseOptions get windows => FirebaseOptions(
    apiKey: AppConfig.instance.firebaseWebApiKey,
    appId: AppConfig.instance.firebaseWebAppId,
    messagingSenderId: AppConfig.instance.firebaseMessagingSenderId,
    projectId: AppConfig.instance.firebaseProjectId,
    authDomain: AppConfig.instance.firebaseAuthDomain,
    storageBucket: AppConfig.instance.firebaseStorageBucket,
    measurementId: AppConfig.instance.firebaseMeasurementId,
  );
}
